# yaml-language-server: $schema=https://json.schemastore.org/golangci-lint.json
version: "2"
linters:
  enable:
    - gocyclo
    - misspell
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "ST1005:"
formatters:
  enable:
    - gofumpt
    - goimports
