# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: etime
    binary: etime_{{.Summary}}
    ldflags:
      - -s -w -X main.version={{.Summary}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
  - id: etime_macos
    binary: etime_{{.Summary}}
    goos:
      - darwin
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - etime_macos
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
archives:
  - formats:
      - tar.gz
    name_template: >-
      etime_
      {{- .Summary }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
changelog:
  disable: true
checksum:
  name_template: "etime_{{ .Summary }}_checksums.txt"
