keys:
  - &theorderingmachine age1dujf55uzev2nnpq6c2drn0e8pmpxay22qqfsavwaxqakwn9se5hsputgx4
  - &zimeg age1exgt6neyetzrg9wgf4vxqmc93sjwqmqm3283hp5zx4m9hy9dpunqh3q4xj
creation_rules:
  - path_regex: vault.json
    key_groups:
      - age:
          - *theorderingmachine
          - *zimeg
