# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Package this version
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  version:
    name: Collect the version
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Collect the current version
        id: tag
        run: |
          echo "$(git describe --dirty --always --tags)"
          echo "version=$(git describe --dirty --always --tags)" >> "$GITHUB_ENV"
          echo "version=$(git describe --dirty --always --tags)" >> "$GITHUB_OUTPUT"
  snapshot:
    name: Save a snapshot
    needs: version
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      version: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - name: Create snapshots
        run: nix develop -c goreleaser release --clean --snapshot --skip=publish --config .goreleaser.staging.yaml
      - name: Mark logged changes
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: etime_${{ env.version }}_CHANGELOG.md
          path: ./CHANGELOG.md
          if-no-files-found: error
      - name: Upload the checksums
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: etime_${{ env.version }}_checksums.txt
          path: ./dist/etime_${{ env.version }}_checksums.txt
          if-no-files-found: error
      - name: Enscribe legal letter
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: etime_${{ env.version }}_LICENSE
          path: ./LICENSE
          if-no-files-found: error
      - name: Read the manual pages
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: etime_${{ env.version }}_man.1
          path: ./etime.1
          if-no-files-found: error
      - name: Write welcoming markdown
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: etime_${{ env.version }}_README.md
          path: ./README.md
          if-no-files-found: error
      - name: Cache the moments
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        if: always()
        with:
          path: ./dist
          key: snapshots-${{ github.sha }}
  artifacts:
    name: Share the artifacts
    needs:
      - snapshot
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      version: ${{ needs.version.outputs.version }}
    strategy:
      matrix:
        target:
          - darwin_arm64.tar.gz
          - darwin_x86_64.tar.gz
          - linux_arm64.tar.gz
          - linux_i386.tar.gz
          - linux_x86_64.tar.gz
          - windows_arm64.zip
          - windows_i386.zip
          - windows_x86_64.zip
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Restore cached snapshots
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ./dist
          key: snapshots-${{ github.sha }}
      - name: Upload a snapshot
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: etime_${{ env.version }}_${{ matrix.target }}
          path: ./dist/etime_${{ env.version }}_${{ matrix.target }}
          if-no-files-found: error
  notify:
    name: Post a notification
    needs: artifacts
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Leave a comment
        run: |
          PR_COMMENT="Latest builds: https://github.com/$GH_REPO/actions/runs/$GH_RUN_ID"
          PR_REF="$GH_REF"
          if [[ "$PR_REF" == *"/merge" ]]; then
            PR_REF="${PR_REF%%/merge}"
          fi
          if ! gh pr comment "$PR_REF" --repo "$GH_REPO" --edit-last --body "$PR_COMMENT"; then
            gh pr comment "$PR_REF" --repo "$GH_REPO" --body "$PR_COMMENT"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF: ${{ github.ref_name }}
          GH_REPO: ${{ github.repository }}
          GH_RUN_ID: ${{ github.run_id }}
  release:
    name: Distribute a release
    needs: version
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      version: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - name: Create releases
        run: |
          nix develop .#tom -c sops exec-env vault.release.json 'goreleaser release --clean --config .goreleaser.release.yaml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOPS_AGE_RELEASE_KEY: ${{ secrets.SOPS_AGE_RELEASE_KEY }}
      - name: Include documentation
        run: |
          gh release upload "$VERSION" "CHANGELOG.md#etime_${VERSION}_CHANGELOG.md"
          gh release upload "$VERSION" "LICENSE#etime_${VERSION}_LICENSE"
          gh release upload "$VERSION" "etime.1#etime_${VERSION}_man.1"
          gh release upload "$VERSION" "README.md#etime_${VERSION}_README.md"
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ env.version }}
