# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Makes valid measurements
on:
  push:
  workflow_dispatch:
jobs:
  checkup:
    name: Inspect the code health
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install dependencies
        run: nix develop -c go get
      - name: Check formatting
        run: nix develop -c make check
      - name: Build binary
        run: nix develop -c make build
      - name: Run tests
        run: nix develop -c make coverage
      - name: Locate Codecov
        id: codecov
        run: echo "binary=$(command -v codecovcli)" >> "$GITHUB_OUTPUT"
      - name: Upload coverage results
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          binary: ${{ steps.codecov.outputs.binary }}
          disable_search: true
          files: coverage/coverage.txt
          override_commit: ${{ github.sha }}
          slug: ${{ github.repository }}
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          verbose: true
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          binary: ${{ steps.codecov.outputs.binary }}
          disable_search: true
          files: coverage/coverage.xml
          override_commit: ${{ github.sha }}
          slug: ${{ github.repository }}
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          verbose: true
  measurement:
    name: Monitor energy usage
    needs: checkup
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Clean the environment
        run: nix develop -c make clean
      - name: Sleep for a short while
        run: |
          nix develop .#tom -c sops exec-env vault.testing.json 'nix run .# sleep 4'
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_TESTING_KEY }}
      - name: Sleep for a bit longer
        run: |
          nix develop .#tom -c sops exec-env vault.testing.json 'nix run .# sleep 12'
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_TESTING_KEY }}
      - name: End with an exit code
        run: |
          set +e
          nix develop .#tom -c sops exec-env vault.testing.json 'nix run .# dream'
          STATUS=$?
          echo $STATUS
          [ "$STATUS" -eq 127 ] || exit 1
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_TESTING_KEY }}
